x-common-config:
  &common-config
  network_mode: host
  ipc: host
  # user: dominik
  volumes:
    - ./shm-only.xml:/shm-only.xml
    # - ./rtps-dump-file.txt:/rtps-dump-file.txt
  environment:
    - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml
    - USER

services:
  talker:
    build: .
    <<: *common-config
    command: ros2 run demo_nodes_cpp talker

  listener:
    build: .
    <<: *common-config
    command: ros2 run demo_nodes_cpp listener
